name: Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download embree
        run: curl -L -O https://github.com/embree/embree/releases/download/v3.13.0/embree-3.13.0.x86_64.linux.tar.gz && tar -xf embree-3.13.0.x86_64.linux.tar.gz && mv embree-3.13.0.x86_64.linux embree

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dembree_DIR=${{github.workspace}}/embree/lib/cmake/embree-3.13.0 -DVIENNARAY_BUILD_TESTS=ON

      - name: Build tests
        # Build program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Trigger Action on ViennaPS Repository
        if: ${{ github.event_name != 'schedule' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_VIENNAPS }}
          repository: yozoon/ViennaPS
          event-type: viennaray-update-linux
