name: macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Download and inflate embree, which is need for testing
      - name: Download embree
        run: curl -L -O https://github.com/embree/embree/releases/download/v3.13.0/embree-3.13.0.x86_64.macosx.zip && tar -xf embree-3.13.0.x86_64.macosx.zip && mv embree-3.13.0.x86_64.macosx embree

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -Dembree_DIR=${{github.workspace}}/embree/lib/cmake/embree-3.13.0 \
            -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" \
            -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" \
            -DOpenMP_C_LIB_NAMES="omp" \
            -DOpenMP_CXX_LIB_NAMES="omp" \
            -DOpenMP_omp_LIBRARY="$(brew --prefix libomp)/lib/libomp.a" \
            -DVIENNARAY_BUILD_TESTS=ON

      - name: Build tests
        # Build program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Trigger Action on ViennaPS Repository
        if: ${{ vars.TRIGGER_VIENNAPS == 'true' && github.event_name != 'schedule' && github.event_name != 'pull_request' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_VIENNAPS }}
          repository: yozoon/ViennaPS
          event-type: viennaray-update-macos
