name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Embree
      run: curl -L -O https://github.com/embree/embree/releases/download/v3.13.0/embree-3.13.0.x64.vc14.windows.zip; tar -xf ${{github.workspace}}/embree-3.13.0.x64.vc14.windows.zip; mv ${{github.workspace}}/embree-3.13.0.x64.vc14.windows/ ${{github.workspace}}/embree/

    - name: Add embree to path
      run: echo "${{github.workspace}}\embree\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dembree_DIR="${{github.workspace}}/embree/lib/cmake/embree-3.13.0" -DVIENNARAY_BUILD_TESTS=ON
      
    - name: Build tests
      # Build program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      run: ctest -C ${{env.BUILD_TYPE}} 